import type { Question } from '@/types';
import type { MainCategory } from '@/types';

export const VIBE_CODING_CATEGORY: MainCategory = {
  id: 'vibe-coding',
  name: 'Vibe Coding',
  emoji: '💻',
  color: '#16C784',
  subcategories: [
    { id: 'vc-tech-skills', mainCategoryId: 'vibe-coding', name: 'Technical Skills & Coding Fundamentals', icon: '🧑‍💻' },
    { id: 'vc-ai-tech', mainCategoryId: 'vibe-coding', name: 'AI & Emerging Technology', icon: '🤖' },
    { id: 'vc-product', mainCategoryId: 'vibe-coding', name: 'Product Development & Entrepreneurship', icon: '🚀' },
    { id: 'vc-team', mainCategoryId: 'vibe-coding', name: 'Team Collaboration & Project Management', icon: '👥' },
    { id: 'vc-gov', mainCategoryId: 'vibe-coding', name: 'Government & Enterprise Solutions', icon: '🏛️' },
    { id: 'vc-community', mainCategoryId: 'vibe-coding', name: 'Community Impact & Social Innovation', icon: '🌍' },
  ],
};

export const VIBE_CODING_QUESTIONS: Question[] = [
  // ─── vc-tech-skills ───
  {
    id: 'q-vc-tech-skills-200-1',
    subcategoryId: 'vc-tech-skills',
    points: 200,
    text: 'What is a variable and why do we use it in programming?',
    answer: 'A variable is a named storage location in memory that holds a value. We use variables to store, reuse, and manipulate data throughout a program — so we don\'t have to repeat the same value over and over.',
    hint: 'Think of it like a labelled box that holds something you want to remember.',
  },
  {
    id: 'q-vc-tech-skills-200-2',
    subcategoryId: 'vc-tech-skills',
    points: 200,
    text: 'What is the difference between a for loop and a while loop?',
    answer: 'A for loop is used when you know in advance how many times you want to iterate. A while loop is used when you want to keep looping as long as a condition is true, and you may not know the exact number of iterations upfront.',
    hint: 'One is for a known count, the other is for an unknown condition.',
  },
  {
    id: 'q-vc-tech-skills-400-1',
    subcategoryId: 'vc-tech-skills',
    points: 400,
    text: 'Explain what recursion is and give a simple real-world example of it.',
    answer: 'Recursion is when a function calls itself to solve a smaller version of the same problem. A real-world example: Russian nesting dolls — each doll contains a smaller doll, until you reach the smallest one (the base case).',
    hint: 'A function that calls itself — think of mirrors facing each other, or nesting dolls.',
  },
  {
    id: 'q-vc-tech-skills-400-2',
    subcategoryId: 'vc-tech-skills',
    points: 400,
    text: 'What is the difference between a stack and a queue? When would you use each one?',
    answer: 'A stack is Last In First Out (LIFO) — the last item added is the first removed. A queue is First In First Out (FIFO) — the first item added is the first removed. Use a stack for undo functionality or call stacks. Use a queue for task scheduling or print jobs.',
    hint: 'Stack = a pile of plates. Queue = a line of people waiting.',
  },
  {
    id: 'q-vc-tech-skills-600-1',
    subcategoryId: 'vc-tech-skills',
    points: 600,
    text: 'What is time complexity and how would you compare O(n log n) vs O(n²) for a sorting problem with a million items?',
    answer: 'Time complexity measures how the runtime of an algorithm grows as input size increases. For 1 million items: O(n log n) ≈ 20 million operations (fast — used by merge sort, quicksort). O(n²) ≈ 1 trillion operations (very slow — used by bubble sort). O(n log n) is dramatically more efficient at scale.',
    hint: 'Think about how many operations each would need for 1,000,000 items.',
  },
  {
    id: 'q-vc-tech-skills-600-2',
    subcategoryId: 'vc-tech-skills',
    points: 600,
    text: 'Explain the concept of memoization and how it differs from dynamic programming.',
    answer: 'Memoization is a top-down technique where you cache the results of expensive function calls so you don\'t recompute them. Dynamic programming is a broader bottom-up approach that builds solutions from smaller subproblems. Memoization is a specific implementation strategy often used within DP.',
    hint: 'Memoization = remember what you calculated. DP = build up the solution from scratch.',
  },

  // ─── vc-ai-tech ───
  {
    id: 'q-vc-ai-tech-200-1',
    subcategoryId: 'vc-ai-tech',
    points: 200,
    text: 'What does AI stand for and can you name one AI tool you use in your everyday life?',
    answer: 'AI stands for Artificial Intelligence. Everyday examples include: ChatGPT, Siri, Google Assistant, Netflix recommendations, spam filters, or facial recognition on your phone.',
    hint: 'Two words — machines acting smart.',
  },
  {
    id: 'q-vc-ai-tech-200-2',
    subcategoryId: 'vc-ai-tech',
    points: 200,
    text: 'What is the difference between AI and a regular computer program?',
    answer: 'A regular computer program follows explicit instructions written by a programmer — it does exactly what it\'s told. AI learns from data and can make decisions or predictions without being explicitly programmed for every scenario.',
    hint: 'One follows rules, the other learns them.',
  },
  {
    id: 'q-vc-ai-tech-400-1',
    subcategoryId: 'vc-ai-tech',
    points: 400,
    text: 'What is the difference between supervised and unsupervised machine learning? Give one example of each.',
    answer: 'Supervised learning trains on labeled data (input + correct output). Example: spam email detection. Unsupervised learning finds patterns in unlabeled data. Example: customer segmentation — grouping shoppers by behavior without predefined categories.',
    hint: 'One has the answer key, the other discovers patterns on its own.',
  },
  {
    id: 'q-vc-ai-tech-400-2',
    subcategoryId: 'vc-ai-tech',
    points: 400,
    text: 'What is a large language model (LLM) and how does it generate text?',
    answer: 'An LLM is a type of AI trained on massive amounts of text data using a transformer architecture. It generates text by predicting the most likely next token (word or word fragment) given the context of previous tokens, based on patterns learned during training.',
    hint: 'It predicts the next word — over and over — based on billions of examples.',
  },
  {
    id: 'q-vc-ai-tech-600-1',
    subcategoryId: 'vc-ai-tech',
    points: 600,
    text: 'What are hallucinations in AI models and what technical strategies exist to reduce them in production systems?',
    answer: 'Hallucinations are when an AI confidently generates false or fabricated information. Strategies to reduce them include: RAG (Retrieval-Augmented Generation), fine-tuning on domain-specific data, grounding outputs with citations, using smaller temperature values, chain-of-thought prompting, and output validation layers.',
    hint: 'The AI makes things up — how do you stop it?',
  },
  {
    id: 'q-vc-ai-tech-600-2',
    subcategoryId: 'vc-ai-tech',
    points: 600,
    text: "Explain the tradeoffs between a fine-tuned model vs a RAG (Retrieval-Augmented Generation) system for a company's internal chatbot.",
    answer: 'Fine-tuning bakes knowledge into model weights — fast inference, but expensive to update and risks forgetting. RAG retrieves fresh documents at query time — easier to update, more transparent, but slower and dependent on retrieval quality. Fine-tuning suits stable knowledge; RAG suits frequently changing data.',
    hint: 'One bakes knowledge in, the other looks it up in real time.',
  },

  // ─── vc-product ───
  {
    id: 'q-vc-product-200-1',
    subcategoryId: 'vc-product',
    points: 200,
    text: 'What is an MVP and why do startups build one instead of a full product?',
    answer: 'MVP stands for Minimum Viable Product — the simplest version of a product that delivers core value and can be tested with real users. Startups build MVPs to validate assumptions, gather feedback, and avoid wasting resources building features nobody wants.',
    hint: 'Minimum Viable Product — the smallest thing that tests your idea.',
  },
  {
    id: 'q-vc-product-200-2',
    subcategoryId: 'vc-product',
    points: 200,
    text: 'What does "product-market fit" mean in simple terms?',
    answer: 'Product-market fit means your product solves a real problem for a real group of people, and those people are willing to pay for it (or use it repeatedly). Signs include strong retention, word-of-mouth growth, and users who would be upset if the product disappeared.',
    hint: 'The moment your product clicks with the people who actually need it.',
  },
  {
    id: 'q-vc-product-400-1',
    subcategoryId: 'vc-product',
    points: 400,
    text: 'Walk us through the difference between a product roadmap and a backlog. How should a PM prioritize features?',
    answer: "A roadmap is a high-level strategic plan showing what will be built and when — it is for stakeholders. A backlog is a detailed list of all tasks, bugs, and features waiting to be worked on. PMs prioritize using frameworks like RICE (Reach, Impact, Confidence, Effort), MoSCoW (Must/Should/Could/Won't), or user impact vs effort grids.",
    hint: 'One is the big picture plan, the other is the to-do list.',
  },
  {
    id: 'q-vc-product-400-2',
    subcategoryId: 'vc-product',
    points: 400,
    text: 'What is A/B testing and how would you use it to improve a sign-up flow?',
    answer: 'A/B testing means running two versions of something simultaneously with different user groups to see which performs better. For a sign-up flow: you might test a shorter form vs a longer one, different CTA button text, or a social login option — then measure completion rates to pick the winner.',
    hint: 'Split your users, test two versions, measure which wins.',
  },
  {
    id: 'q-vc-product-600-1',
    subcategoryId: 'vc-product',
    points: 600,
    text: 'A product has strong engagement but low retention after 30 days. Walk through how you would diagnose and fix the retention problem using data.',
    answer: 'Start by mapping the user journey and identifying where drop-off happens using funnel analysis and cohort retention charts. Look at what actions retained users take vs churned users in the first week (the "aha moment"). Fix by: improving onboarding, adding re-engagement emails, reducing time-to-value, and addressing friction points identified through session recordings and user interviews.',
    hint: 'Look at what retained users do differently in their first 7 days.',
  },
  {
    id: 'q-vc-product-600-2',
    subcategoryId: 'vc-product',
    points: 600,
    text: 'How would you decide whether to build, buy, or partner when adding a new feature to a growing SaaS platform?',
    answer: 'Build when the feature is core to your differentiation and you have the engineering capacity. Buy (acquire or license) when speed matters and a solution already exists. Partner when the feature is complementary and integration is faster than building. Key factors: time-to-market, cost, strategic importance, and whether you want to own the data and IP.',
    hint: 'Core differentiator = build. Commodity feature = buy. Complementary = partner.',
  },

  // ─── vc-team ───
  {
    id: 'q-vc-team-200-1',
    subcategoryId: 'vc-team',
    points: 200,
    text: 'What is version control and why is it important for a team of developers?',
    answer: 'Version control (like Git) tracks changes to code over time, lets multiple developers work simultaneously without overwriting each other, and allows you to roll back to any previous state. It is essential for collaboration, code review, and maintaining a history of what changed and why.',
    hint: 'Think of it as a time machine and collaborative workspace for your code.',
  },
  {
    id: 'q-vc-team-200-2',
    subcategoryId: 'vc-team',
    points: 200,
    text: 'What does "agile" mean in a software development context?',
    answer: 'Agile is an iterative approach to software development where work is broken into short cycles called sprints (usually 1–2 weeks). Teams deliver working software frequently, adapt to changing requirements, and prioritize collaboration with customers over rigid up-front planning.',
    hint: 'Short cycles, frequent delivery, constant feedback.',
  },
  {
    id: 'q-vc-team-400-1',
    subcategoryId: 'vc-team',
    points: 400,
    text: 'What is the difference between a Git merge and a Git rebase? When would you use each?',
    answer: 'A merge combines two branches and creates a new merge commit — it preserves the full history. A rebase moves your commits on top of another branch, creating a linear history as if the work was done sequentially. Use merge for shared/public branches to preserve history. Use rebase for local feature branches to keep history clean before merging.',
    hint: 'Merge preserves history with a join point. Rebase rewrites it to look linear.',
  },
  {
    id: 'q-vc-team-400-2',
    subcategoryId: 'vc-team',
    points: 400,
    text: 'How would you handle a situation where two team members have a conflict over the direction of a feature?',
    answer: 'Bring both parties together to clearly define the problem they are solving and the user need. Use data (user research, metrics) to ground the discussion rather than opinions. If still unresolved, involve the PM to make the call based on product strategy. Document the decision and rationale so everyone moves forward aligned.',
    hint: 'Anchor to the user problem and data, not personal preference.',
  },
  {
    id: 'q-vc-team-600-1',
    subcategoryId: 'vc-team',
    points: 600,
    text: 'Your team is two weeks from a deadline and a critical bug is discovered that could delay launch. Walk through how you would triage, communicate, and make a go/no-go decision.',
    answer: 'Immediately assess severity: does the bug affect core functionality or just edge cases? Assign your best engineers to investigate and estimate fix time. Communicate transparently with stakeholders — give a clear update within hours. Evaluate options: fix before launch, launch with a workaround, or delay. Make a go/no-go decision based on user impact, risk, and business cost of delay. Document the decision.',
    hint: 'Assess → communicate → options → decide → document.',
  },
  {
    id: 'q-vc-team-600-2',
    subcategoryId: 'vc-team',
    points: 600,
    text: 'Describe how you would set up a CI/CD pipeline for a team of 10 engineers shipping multiple times a week.',
    answer: 'CI: Every pull request triggers automated tests (unit, integration), linting, and a build check. No merge without passing CI. CD: On merge to main, automatically deploy to a staging environment. Use feature flags to separate deployment from release. After QA sign-off, promote to production — either manually or automatically. Add rollback capability, monitoring alerts, and deployment notifications in Slack.',
    hint: 'PR triggers tests → merge deploys to staging → promote to prod with rollback.',
  },

  // ─── vc-gov ───
  {
    id: 'q-vc-gov-200-1',
    subcategoryId: 'vc-gov',
    points: 200,
    text: 'What is one key difference between building a consumer app vs an enterprise software product?',
    answer: 'Consumer apps prioritize ease of use, viral growth, and fast onboarding for individual users. Enterprise software must serve organizational needs — with role-based access, security compliance, integration with existing tools, and a longer sales cycle involving procurement teams rather than individual decisions.',
    hint: 'One sells to a person, the other sells to an organization.',
  },
  {
    id: 'q-vc-gov-200-2',
    subcategoryId: 'vc-gov',
    points: 200,
    text: 'Why do government contracts typically take longer to close than commercial ones?',
    answer: 'Government procurement involves formal RFP (Request for Proposal) processes, multiple approval layers, budget cycles (often annual), compliance requirements, legal reviews, and in some cases mandatory competitive bidding. These processes are designed for accountability and fairness but significantly extend timelines compared to commercial deals.',
    hint: 'Budget cycles, RFPs, and layers of approval all slow things down.',
  },
  {
    id: 'q-vc-gov-400-1',
    subcategoryId: 'vc-gov',
    points: 400,
    text: 'What is FedRAMP and why does it matter for companies selling software to US government agencies?',
    answer: 'FedRAMP (Federal Risk and Authorization Management Program) is a US government framework that standardizes the security assessment and authorization of cloud services used by federal agencies. A company must be FedRAMP authorized for their cloud product before most federal agencies can use it. It is a major compliance gate — expensive and time-consuming to achieve, but it opens access to the full federal market.',
    hint: 'It is the security stamp of approval cloud vendors need to sell to US federal agencies.',
  },
  {
    id: 'q-vc-gov-400-2',
    subcategoryId: 'vc-gov',
    points: 400,
    text: "What does \"scalability\" mean and what is one architectural decision that affects it early in a product's life?",
    answer: 'Scalability means the system can handle growing amounts of work or users without degrading performance. A critical early decision is choosing between a monolithic architecture (all code in one deployable unit — simple but hard to scale individual components) vs a microservices architecture (independent services — harder to set up but scales components separately). Database choice (SQL vs NoSQL, vertical vs horizontal scaling) is another key early decision.',
    hint: 'Can your system grow without breaking? Monolith vs microservices is one early fork.',
  },
  {
    id: 'q-vc-gov-600-1',
    subcategoryId: 'vc-gov',
    points: 600,
    text: 'A government client requires your software to be FIPS 140-2 compliant. Explain what that means and how it would affect your system architecture.',
    answer: 'FIPS 140-2 is a US federal standard for cryptographic modules — it mandates using only approved encryption algorithms (like AES-256, SHA-256) and validated cryptographic libraries. This affects: all data-at-rest and in-transit encryption, key management systems, TLS configuration, and any third-party libraries used for crypto. You may need to use FIPS-validated builds of OpenSSL and restrict cipher suites. It limits your tech choices and requires compliance documentation.',
    hint: 'It is a federal encryption standard — it restricts which crypto algorithms and libraries you can use.',
  },
  {
    id: 'q-vc-gov-600-2',
    subcategoryId: 'vc-gov',
    points: 600,
    text: 'Compare a multi-tenant SaaS architecture vs a single-tenant deployment model from a security, cost, and compliance standpoint for a government customer.',
    answer: 'Multi-tenant: all customers share infrastructure — lower cost, easier to maintain, but harder to meet strict data isolation requirements. Government clients often reject this for sensitive data. Single-tenant: each customer gets their own isolated environment — higher cost and operational overhead, but full data isolation, easier compliance (FedRAMP, FISMA), and customizable security controls. Government and regulated industries typically require single-tenant or at minimum a "GovCloud" isolated region.',
    hint: 'Shared infrastructure = cheaper but harder to isolate. Dedicated = expensive but government-ready.',
  },

  // ─── vc-community ───
  {
    id: 'q-vc-community-200-1',
    subcategoryId: 'vc-community',
    points: 200,
    text: 'What does "tech for social good" mean to you? Give one real example of technology helping a community.',
    answer: 'Accept any well-reasoned answer. Examples: Duolingo providing free language education globally, GiveDirectly using mobile money to deliver cash aid in Africa, Khan Academy making education accessible, or apps helping connect food banks with surplus food donors. The key idea is technology applied to a social challenge with measurable community benefit.',
    hint: 'Any real technology that solves a problem for underserved people.',
  },
  {
    id: 'q-vc-community-200-2',
    subcategoryId: 'vc-community',
    points: 200,
    text: 'Why is diversity in tech teams important for building better products?',
    answer: 'Diverse teams bring different perspectives, experiences, and ways of thinking — which leads to identifying blind spots, building for a wider range of users, and avoiding biased design. Products built by homogeneous teams often exclude or poorly serve users who are different from the builders. Research also shows diverse teams make better decisions and are more innovative.',
    hint: 'If everyone on the team looks the same, who are you accidentally excluding?',
  },
  {
    id: 'q-vc-community-400-1',
    subcategoryId: 'vc-community',
    points: 400,
    text: 'What is the digital divide and what are two practical ways a tech company can help reduce it?',
    answer: 'The digital divide is the gap between people who have reliable access to the internet, devices, and digital skills vs those who do not — often split along lines of income, geography, age, or disability. Companies can help by: (1) building lightweight apps that work on low-end devices and slow connections, (2) partnering with nonprofits to offer subsidized access or devices, (3) creating offline-first features, or (4) investing in digital literacy programs in underserved communities.',
    hint: 'Not everyone has a fast phone and WiFi — how do you design and act with that in mind?',
  },
  {
    id: 'q-vc-community-400-2',
    subcategoryId: 'vc-community',
    points: 400,
    text: 'How would you measure the real-world impact of a community coding education program?',
    answer: 'Go beyond vanity metrics (enrollment numbers). Measure: job placement rates and salary changes 6–12 months post-graduation, percentage who complete the program (retention), diversity of participants, whether graduates contribute back as mentors, employer satisfaction scores, and long-term career trajectory. Also measure community-level indicators like local tech employment rates over time.',
    hint: 'Did people actually get jobs and better lives? That is the real metric.',
  },
  {
    id: 'q-vc-community-600-1',
    subcategoryId: 'vc-community',
    points: 600,
    text: 'A city government wants to use an AI system to allocate social services. What ethical risks exist and how would you design a system that is fair and auditable?',
    answer: "Risks include: algorithmic bias (the model may reflect historical discrimination), lack of transparency (recipients don't know why they were denied), no human appeal process, data privacy violations, and feedback loops that entrench inequality. Design safeguards: use diverse and representative training data, build explainability into the model (not black-box), require human review for all denial decisions, create a public appeals process, publish audit reports regularly, and involve community stakeholders in the design process.",
    hint: 'Who does the AI hurt if it gets it wrong? How do you explain and challenge its decisions?',
  },
  {
    id: 'q-vc-community-600-2',
    subcategoryId: 'vc-community',
    points: 600,
    text: 'How would you build a sustainable open-source community around a civic tech tool without full-time funding?',
    answer: 'Start with a clear mission and documented problem the tool solves. Make contribution easy: good README, CONTRIBUTING guide, labeled "good first issues". Build a community home (Discord, forum) and recognize contributors publicly. Find institutional partners (universities, nonprofits, gov agencies) who benefit and can donate time or small grants. Apply for open-source grants (Mozilla, Ford Foundation, GitHub Sponsors). Grow a governance model so it does not depend on one person. Sustainability comes from distributed ownership and clear value.',
    hint: 'Good docs, easy onboarding, institutional partners, and distributed ownership.',
  },
];
